apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: demo-che
  labels:
    app: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        # image: eche21/helloapp:9
        image:  eche21/helloapp:17_
        #image: $DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_RUN_NUMBER
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: helloworld-service
  namespace: demo-che
spec:
  selector:
    app: helloworld
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer #NodePort