# Atlas Build Pipeline
# Triggers only on PR's to the Atlas master branch. 

# 1. Builds Atlas image, tags image with 'prod' and 'commit-sha', and pushes to ACR.
# 2. Create and run DB Migration script on the QA database
# 3. Deploy image to QA 

name: build_and_deploy_hello_world

on:
  push:
    branches:
      - 'main'
      