# Atlas Build Pipeline
# Triggers only on PR's to the Atlas master branch. 

# 1. Builds Atlas image, tags image with 'prod' and 'commit-sha', and pushes to ACR.
# 2. Create and run DB Migration script on the QA database
# 3. Deploy image to QA 

name: build_and_deploy_hello_world

on:
  push:
    branches:
      - 'master'
      - 'che'

#Builds the image
  - stage: Build
    jobs: 
    - job: Build_Push_Image
      displayName: Build_Push_Image
      steps:
        - script: |
            echo "##vso[task.setvariable variable=commit-tag;isOutput=true]$(echo $BUILD_SOURCEVERSION | cut -c 1-7)"
          name: setCommitTag
          displayName: 'Set Commit Tag'
        
        - script: echo Commit tag is $(setCommitTag.commit-tag)
          displayName: 'Display Commit Tag'

        - task: Docker@2
          displayName: 'Build Image and Push to DockerHub'
          inputs:
            containerRegistry: 'Docker Hub - eche21'
            repository: 'helloworld_repo'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: |
              $(setCommitTag.commit-tag)
        - script: |
            docker image ls
            #docker tag c2labs/atlas-c2internal:$(setCommitTag.commit-tag) c2labs.azurecr.io/atlas:$(setCommitTag.commit-tag) 
            #docker image ls
          displayName: 'Retag for ACR'              